{
   "success":1,
   "entities":{
      "Q3390720":{
         "lastrevid":1775896495,
         "pageid":3231294,
         "claims":{
            "P625":[
               {
                  "type":"statement",
                  "id":"Q3390720$b98f722c-098f-4780-ad7b-589611a22fa2",
                  "rank":"normal",
                  "mainsnak":{
                     "snaktype":"value",
                     "datatype":"globe-coordinate",
                     "datavalue":{
                        "type":"globecoordinate",
                        "value":{
                           "altitude":null,
                           "globe":"http://www.wikidata.org/entity/Q2",
                           "longitude":-1.6778,
                           "precision":0.00027777777777778,
                           "latitude":48.1119
                        }
                     },
                     "hash":"bc26b1c88abcca6ab31f5d89c496972e7b8ee28f",
                     "property":"P625"
                  }
               }
            ],
            "P47":[
               {
                  "type":"statement",
                  "rank":"normal",
                  "id":"Q3390720$5150c592-4b0f-03cd-ee45-8884ad6550ad",
                  "mainsnak":{
                     "datavalue":{
                        "type":"wikibase-entityid",
                        "value":{
                           "id":"Q19975163",
                           "entity-type":"item",
                           "numeric-id":19975163
                        }
                     },
                     "hash":"c6bf0154384f516722c7462461445b4eeddb3d9e",
                     "property":"P47",
                     "snaktype":"value",
                     "datatype":"wikibase-item"
                  }
               },
               {
                  "mainsnak":{
                     "datatype":"wikibase-item",
                     "snaktype":"value",
                     "hash":"ef8bc06d15175a5d56ab7b412d97012200284282",
                     "property":"P47",
                     "datavalue":{
                        "value":{
                           "entity-type":"item",
                           "numeric-id":3449878,
                           "id":"Q3449878"
                        },
                        "type":"wikibase-entityid"
                     }
                  },
                  "id":"Q3390720$79abac35-4c3d-af1d-908d-bec674d64a20",
                  "rank":"normal",
                  "type":"statement"
               },
               {
                  "mainsnak":{
                     "datavalue":{
                        "type":"wikibase-entityid",
                        "value":{
                           "entity-type":"item",
                           "numeric-id":20018625,
                           "id":"Q20018625"
                        }
                     },
                     "hash":"542bdb6897d3a429ccdf3cc3be98237d715357e5",
                     "property":"P47",
                     "snaktype":"value",
                     "datatype":"wikibase-item"
                  },
                  "rank":"normal",
                  "id":"Q3390720$8865abf2-45bf-25db-111c-14a3473fc0b6",
                  "type":"statement"
               },
               {
                  "type":"statement",
                  "mainsnak":{
                     "datatype":"wikibase-item",
                     "snaktype":"value",
                     "property":"P47",
                     "hash":"b5a2ae9ef81f64b99341f718e448a0706a9cc25f",
                     "datavalue":{
                        "value":{
                           "id":"Q21681017",
                           "entity-type":"item",
                           "numeric-id":21681017
                        },
                        "type":"wikibase-entityid"
                     }
                  },
                  "id":"Q3390720$46dac533-4ab2-ab4f-4030-21aafebfbd70",
                  "rank":"normal"
               },
               {
                  "type":"statement",
                  "rank":"normal",
                  "id":"Q3390720$53ad57ab-4b4c-7649-4361-2a243dbfb7f5",
                  "mainsnak":{
                     "datavalue":{
                        "value":{
                           "entity-type":"item",
                           "numeric-id":23010183,
                           "id":"Q23010183"
                        },
                        "type":"wikibase-entityid"
                     },
                     "hash":"4cfbeadab752e1fe5da4f10d9d570b41aa214d15",
                     "property":"P47",
                     "snaktype":"value",
                     "datatype":"wikibase-item"
                  }
               },
               {
                  "id":"Q3390720$B718CCA3-3548-4942-B247-1AF9BA796168",
                  "rank":"normal",
                  "mainsnak":{
                     "datavalue":{
                        "value":{
                           "numeric-id":23297225,
                           "entity-type":"item",
                           "id":"Q23297225"
                        },
                        "type":"wikibase-entityid"
                     },
                     "hash":"385115c2373fd31b2fe28c841bda66515be19657",
                     "property":"P47",
                     "snaktype":"value",
                     "datatype":"wikibase-item"
                  },
                  "type":"statement"
               },
               {
                  "rank":"normal",
                  "id":"Q3390720$48B3A4D8-919A-40FE-8825-A66CA1513447",
                  "mainsnak":{
                     "hash":"839fa796513eb01c63ada5f836d085d14b1f7c2a",
                     "property":"P47",
                     "datavalue":{
                        "type":"wikibase-entityid",
                        "value":{
                           "entity-type":"item",
                           "numeric-id":23297641,
                           "id":"Q23297641"
                        }
                     },
                     "datatype":"wikibase-item",
                     "snaktype":"value"
                  },
                  "type":"statement"
               }
            ],
            "P31":[
               {
                  "references":[
                     {
                        "snaks":{
                           "P248":[
                              {
                                 "hash":"fc376b4e25f8c58fa7210b660e00a66558a3332b",
                                 "property":"P248",
                                 "datavalue":{
                                    "type":"wikibase-entityid",
                                    "value":{
                                       "id":"Q809830",
                                       "numeric-id":809830,
                                       "entity-type":"item"
                                    }
                                 },
                                 "datatype":"wikibase-item",
                                 "snaktype":"value"
                              }
                           ]
                        },
                        "snaks-order":[
                           "P248"
                        ],
                        "hash":"d709174cc609072fbf310bb52ddfb7aa2332b473"
                     }
                  ],
                  "type":"statement",
                  "mainsnak":{
                     "snaktype":"value",
                     "datatype":"wikibase-item",
                     "datavalue":{
                        "type":"wikibase-entityid",
                        "value":{
                           "entity-type":"item",
                           "numeric-id":174782,
                           "id":"Q174782"
                        }
                     },
                     "property":"P31",
                     "hash":"844f00cf55ac546d0e67c23e7e417559ec8d37c9"
                  },
                  "id":"Q3390720$4295b787-47be-744c-54e3-ed993ee38e59",
                  "rank":"normal"
               }
            ],
            "P3182":[
               {
                  "qualifiers-order":[
                     "P580",
                     "P1810"
                  ],
                  "qualifiers":{
                     "P1810":[
                        {
                           "datatype":"string",
                           "snaktype":"value",
                           "hash":"b7a8acaabb283c0b1374ac558aeb57c91ca4c489",
                           "property":"P1810",
                           "datavalue":{
                              "type":"string",
                              "value":"PLACE DU PARLEMENT DE BRETAGNE"
                           }
                        }
                     ],
                     "P580":[
                        {
                           "hash":"be1e2dce0d9484a401f086816d725aa8a2741104",
                           "property":"P580",
                           "datavalue":{
                              "type":"time",
                              "value":{
                                 "before":0,
                                 "after":0,
                                 "time":"+1987-01-01T00:00:00Z",
                                 "precision":11,
                                 "calendarmodel":"http://www.wikidata.org/entity/Q1985727",
                                 "timezone":0
                              }
                           },
                           "datatype":"time",
                           "snaktype":"value"
                        }
                     ]
                  },
                  "type":"statement",
                  "id":"Q3390720$4E90975B-BE6D-419A-9723-E70D0C4A23B9",
                  "rank":"normal",
                  "mainsnak":{
                     "datavalue":{
                        "value":"3502387095N",
                        "type":"string"
                     },
                     "hash":"75a4bddda567dad4123e1717c4805ca0d185d57d",
                     "property":"P3182",
                     "snaktype":"value",
                     "datatype":"external-id"
                  },
                  "references":[
                     {
                        "hash":"a4281672246eceb72bc4c6fd0486a3ad3e28df4d",
                        "snaks-order":[
                           "P248",
                           "P813",
                           "P854"
                        ],
                        "snaks":{
                           "P813":[
                              {
                                 "snaktype":"value",
                                 "datatype":"time",
                                 "datavalue":{
                                    "type":"time",
                                    "value":{
                                       "precision":11,
                                       "time":"+2022-03-17T00:00:00Z",
                                       "after":0,
                                       "before":0,
                                       "calendarmodel":"http://www.wikidata.org/entity/Q1985727",
                                       "timezone":0
                                    }
                                 },
                                 "property":"P813",
                                 "hash":"68ec24073dbaa625343d470b243b5a7931681852"
                              }
                           ],
                           "P248":[
                              {
                                 "snaktype":"value",
                                 "datatype":"wikibase-item",
                                 "datavalue":{
                                    "type":"wikibase-entityid",
                                    "value":{
                                       "id":"Q3066631",
                                       "entity-type":"item",
                                       "numeric-id":3066631
                                    }
                                 },
                                 "property":"P248",
                                 "hash":"28115795a8258272d116c003a5a33662068027b8"
                              }
                           ],
                           "P854":[
                              {
                                 "snaktype":"value",
                                 "datatype":"url",
                                 "datavalue":{
                                    "type":"string",
                                    "value":"https://adresse.data.gouv.fr/fantoir/departement/35/commune/35238"
                                 },
                                 "hash":"31f295d5315ff01b2236ff441a22de3dd5a6d6c8",
                                 "property":"P854"
                              }
                           ]
                        }
                     }
                  ]
               }
            ],
            "P2561":[
               {
                  "type":"statement",
                  "references":[
                     {
                        "snaks":{
                           "P854":[
                              {
                                 "property":"P854",
                                 "hash":"9cee7325a6e6455642a14e401d51641d70dd7fe3",
                                 "datavalue":{
                                    "type":"string",
                                    "value":"https://data.rennesmetropole.fr/explore/dataset/nom_voies_breton/information/"
                                 },
                                 "datatype":"url",
                                 "snaktype":"value"
                              }
                           ]
                        },
                        "snaks-order":[
                           "P854"
                        ],
                        "hash":"f9454d8280f9e35efb73d3674efc633bf407de8e"
                     }
                  ],
                  "rank":"normal",
                  "id":"Q3390720$0F2086A9-242C-408E-B56F-88DA4C3EE167",
                  "mainsnak":{
                     "hash":"90ae80a5082befd45e1820505b702a2c2e031239",
                     "property":"P2561",
                     "datavalue":{
                        "type":"monolingualtext",
                        "value":{
                           "language":"br",
                           "text":"plasenn Breujoù Breizh"
                        }
                     },
                     "datatype":"monolingualtext",
                     "snaktype":"value"
                  }
               }
            ],
            "P18":[
               {
                  "type":"statement",
                  "mainsnak":{
                     "datavalue":{
                        "type":"string",
                        "value":"PlaceParlementBretagne.jpg"
                     },
                     "hash":"93a7fd5edd7ced644573c87644c93aaa99d295f9",
                     "property":"P18",
                     "snaktype":"value",
                     "datatype":"commonsMedia"
                  },
                  "id":"Q3390720$4AF5639B-202C-4813-BE54-416532453DD9",
                  "rank":"normal"
               }
            ],
            "P373":[
               {
                  "mainsnak":{
                     "datavalue":{
                        "value":"Place du parlement de Bretagne",
                        "type":"string"
                     },
                     "hash":"ed54b8c8d657184e4a613215a950811c7dad7fa4",
                     "property":"P373",
                     "snaktype":"value",
                     "datatype":"string"
                  },
                  "id":"q3390720$95EB9A9B-99B7-426D-9437-29F1E9DA1D33",
                  "rank":"normal",
                  "type":"statement"
               }
            ],
            "P2671":[
               {
                  "type":"statement",
                  "mainsnak":{
                     "property":"P2671",
                     "hash":"9652ad63423d30adf2dee73955ede60950f36354",
                     "datavalue":{
                        "value":"/g/11b76fy7h8",
                        "type":"string"
                     },
                     "datatype":"external-id",
                     "snaktype":"value"
                  },
                  "rank":"normal",
                  "id":"Q3390720$A0FC556B-DCE7-4D3E-BBAB-D8D2151B84E0"
               }
            ],
            "P1435":[
               {
                  "mainsnak":{
                     "datatype":"wikibase-item",
                     "snaktype":"value",
                     "hash":"47d4f633ccb039ebb1a08af61dffb908b5e07611",
                     "property":"P1435",
                     "datavalue":{
                        "value":{
                           "entity-type":"item",
                           "numeric-id":10387684,
                           "id":"Q10387684"
                        },
                        "type":"wikibase-entityid"
                     }
                  },
                  "id":"Q3390720$6215F420-74EB-4219-A41D-8D93135F64E0",
                  "rank":"normal",
                  "references":[
                     {
                        "hash":"d709174cc609072fbf310bb52ddfb7aa2332b473",
                        "snaks-order":[
                           "P248"
                        ],
                        "snaks":{
                           "P248":[
                              {
                                 "snaktype":"value",
                                 "datatype":"wikibase-item",
                                 "datavalue":{
                                    "value":{
                                       "entity-type":"item",
                                       "numeric-id":809830,
                                       "id":"Q809830"
                                    },
                                    "type":"wikibase-entityid"
                                 },
                                 "hash":"fc376b4e25f8c58fa7210b660e00a66558a3332b",
                                 "property":"P248"
                              }
                           ]
                        }
                     }
                  ],
                  "qualifiers-order":[
                     "P580"
                  ],
                  "qualifiers":{
                     "P580":[
                        {
                           "datavalue":{
                              "value":{
                                 "precision":11,
                                 "after":0,
                                 "before":0,
                                 "time":"+1942-10-29T00:00:00Z",
                                 "calendarmodel":"http://www.wikidata.org/entity/Q1985727",
                                 "timezone":0
                              },
                              "type":"time"
                           },
                           "property":"P580",
                           "hash":"842ceb48f0636eb4da2c28a8956e80079fd6ae0f",
                           "snaktype":"value",
                           "datatype":"time"
                        }
                     ]
                  },
                  "type":"statement"
               }
            ],
            "P131":[
               {
                  "id":"Q3390720$B90E4C90-08AD-4196-9AD2-827B01C1BE08",
                  "rank":"normal",
                  "mainsnak":{
                     "datavalue":{
                        "type":"wikibase-entityid",
                        "value":{
                           "numeric-id":647,
                           "entity-type":"item",
                           "id":"Q647"
                        }
                     },
                     "property":"P131",
                     "hash":"a964723de447ff6c543f356019ab9689f3eb5de2",
                     "snaktype":"value",
                     "datatype":"wikibase-item"
                  },
                  "type":"statement",
                  "references":[
                     {
                        "snaks":{
                           "P248":[
                              {
                                 "snaktype":"value",
                                 "datatype":"wikibase-item",
                                 "datavalue":{
                                    "type":"wikibase-entityid",
                                    "value":{
                                       "id":"Q809830",
                                       "numeric-id":809830,
                                       "entity-type":"item"
                                    }
                                 },
                                 "property":"P248",
                                 "hash":"fc376b4e25f8c58fa7210b660e00a66558a3332b"
                              }
                           ]
                        },
                        "snaks-order":[
                           "P248"
                        ],
                        "hash":"d709174cc609072fbf310bb52ddfb7aa2332b473"
                     }
                  ]
               }
            ],
            "P1766":[
               {
                  "qualifiers":{
                     "P407":[
                        {
                           "snaktype":"value",
                           "datatype":"wikibase-item",
                           "datavalue":{
                              "value":{
                                 "entity-type":"item",
                                 "numeric-id":150,
                                 "id":"Q150"
                              },
                              "type":"wikibase-entityid"
                           },
                           "property":"P407",
                           "hash":"d197d0a5efa4b4c23a302a829dd3ef43684fe002"
                        }
                     ]
                  },
                  "type":"statement",
                  "qualifiers-order":[
                     "P407"
                  ],
                  "id":"Q3390720$a74e3c19-42b3-4fb2-286b-cc4ceba1912b",
                  "rank":"normal",
                  "mainsnak":{
                     "datatype":"commonsMedia",
                     "snaktype":"value",
                     "property":"P1766",
                     "hash":"6ea39f35d89fddc52b539ea6f2116185fe005b09",
                     "datavalue":{
                        "value":"Street signs in Rennes.jpg",
                        "type":"string"
                     }
                  }
               }
            ],
            "P380":[
               {
                  "references":[
                     {
                        "snaks-order":[
                           "P248"
                        ],
                        "snaks":{
                           "P248":[
                              {
                                 "datatype":"wikibase-item",
                                 "snaktype":"value",
                                 "property":"P248",
                                 "hash":"fc376b4e25f8c58fa7210b660e00a66558a3332b",
                                 "datavalue":{
                                    "type":"wikibase-entityid",
                                    "value":{
                                       "numeric-id":809830,
                                       "entity-type":"item",
                                       "id":"Q809830"
                                    }
                                 }
                              }
                           ]
                        },
                        "hash":"d709174cc609072fbf310bb52ddfb7aa2332b473"
                     }
                  ],
                  "type":"statement",
                  "mainsnak":{
                     "datavalue":{
                        "value":"PA00090752",
                        "type":"string"
                     },
                     "hash":"31e9040c5d32c04dd43e761dd47fdf8b6d304ede",
                     "property":"P380",
                     "snaktype":"value",
                     "datatype":"external-id"
                  },
                  "id":"Q3390720$A7287D24-FAF9-4685-8892-5AAC6DE31692",
                  "rank":"normal"
               }
            ],
            "P127":[
               {
                  "references":[
                     {
                        "snaks":{
                           "P248":[
                              {
                                 "datavalue":{
                                    "type":"wikibase-entityid",
                                    "value":{
                                       "entity-type":"item",
                                       "numeric-id":809830,
                                       "id":"Q809830"
                                    }
                                 },
                                 "property":"P248",
                                 "hash":"fc376b4e25f8c58fa7210b660e00a66558a3332b",
                                 "snaktype":"value",
                                 "datatype":"wikibase-item"
                              }
                           ]
                        },
                        "snaks-order":[
                           "P248"
                        ],
                        "hash":"d709174cc609072fbf310bb52ddfb7aa2332b473"
                     }
                  ],
                  "type":"statement",
                  "mainsnak":{
                     "property":"P127",
                     "hash":"660cb23540ef2209a739959a8b1bf9b93ca2e2f9",
                     "datavalue":{
                        "type":"wikibase-entityid",
                        "value":{
                           "numeric-id":86604751,
                           "entity-type":"item",
                           "id":"Q86604751"
                        }
                     },
                     "datatype":"wikibase-item",
                     "snaktype":"value"
                  },
                  "rank":"normal",
                  "id":"Q3390720$9097BEDD-BC53-4845-B2BB-D52EBDD5CBE7"
               }
            ],
            "P8467":[
               {
                  "mainsnak":{
                     "datatype":"external-id",
                     "snaktype":"value",
                     "hash":"5e90e0cb49738f6b2edcbb8b13183cbdda2f4093",
                     "property":"P8467",
                     "datavalue":{
                        "type":"string",
                        "value":"Place_du_Parlement_de_Bretagne"
                     }
                  },
                  "id":"Q3390720$49DD3CF8-4132-4ACE-8392-5A00B7510F56",
                  "rank":"normal",
                  "type":"statement"
               }
            ],
            "P17":[
               {
                  "rank":"normal",
                  "id":"q3390720$25CFAFEE-D1DE-4BC7-A85F-48DAE6ACCDBB",
                  "mainsnak":{
                     "datatype":"wikibase-item",
                     "snaktype":"value",
                     "hash":"c05db5d169c2560b9799d567a803d20a392f53e4",
                     "property":"P17",
                     "datavalue":{
                        "type":"wikibase-entityid",
                        "value":{
                           "id":"Q142",
                           "numeric-id":142,
                           "entity-type":"item"
                        }
                     }
                  },
                  "type":"statement",
                  "references":[
                     {
                        "hash":"d709174cc609072fbf310bb52ddfb7aa2332b473",
                        "snaks":{
                           "P248":[
                              {
                                 "snaktype":"value",
                                 "datatype":"wikibase-item",
                                 "datavalue":{
                                    "value":{
                                       "numeric-id":809830,
                                       "entity-type":"item",
                                       "id":"Q809830"
                                    },
                                    "type":"wikibase-entityid"
                                 },
                                 "hash":"fc376b4e25f8c58fa7210b660e00a66558a3332b",
                                 "property":"P248"
                              }
                           ]
                        },
                        "snaks-order":[
                           "P248"
                        ]
                     }
                  ]
               }
            ],
            "P138":[
               {
                  "type":"statement",
                  "id":"Q3390720$8a8f3694-4f48-1edf-4702-66556425256a",
                  "rank":"normal",
                  "mainsnak":{
                     "snaktype":"value",
                     "datatype":"wikibase-item",
                     "datavalue":{
                        "value":{
                           "numeric-id":2500775,
                           "entity-type":"item",
                           "id":"Q2500775"
                        },
                        "type":"wikibase-entityid"
                     },
                     "hash":"ebe49c3e1e70564f7a8b04cd86dcc47467cbf1ed",
                     "property":"P138"
                  }
               },
               {
                  "type":"statement",
                  "rank":"preferred",
                  "id":"Q3390720$938f52ef-410b-3143-8125-819c632b2fb4",
                  "mainsnak":{
                     "hash":"fbb2945df74ae4fd18f3d5f6f4004d9945f368bb",
                     "property":"P138",
                     "datavalue":{
                        "value":{
                           "entity-type":"item",
                           "numeric-id":2351981,
                           "id":"Q2351981"
                        },
                        "type":"wikibase-entityid"
                     },
                     "datatype":"wikibase-item",
                     "snaktype":"value"
                  }
               }
            ]
         },
         "title":"Q3390720",
         "aliases":{
            "fr":[
               {
                  "value":"place du Parlement de Bretagne",
                  "language":"fr"
               },
               {
                  "value":"place du Parlement",
                  "language":"fr"
               },
               {
                  "value":"place Louis-le-Grand",
                  "language":"fr"
               },
               {
                  "language":"fr",
                  "value":"place de l’Égalité"
               }
            ],
            "br":[
               {
                  "language":"br",
                  "value":"leurgêr Breujoù Breizh"
               }
            ]
         },
         "id":"Q3390720",
         "ns":0,
         "sitelinks":{
            "zhwiki":{
               "title":"布列塔尼议会广场",
               "badges":[],
               "site":"zhwiki"
            },
            "brwiki":{
               "title":"Plasenn Breujoù Breizh",
               "site":"brwiki",
               "badges":[]
            },
            "frwiki":{
               "badges":[],
               "site":"frwiki",
               "title":"Place du Parlement-de-Bretagne"
            },
            "commonswiki":{
               "site":"commonswiki",
               "badges":[],
               "title":"Category:Place du parlement de Bretagne"
            }
         },
         "descriptions":{
            "ar":{
               "language":"ar",
               "value":"ميدان في رين، فرنسا"
            },
            "nl":{
               "language":"nl",
               "value":"plein in Rennes"
            },
            "en":{
               "value":"square in Rennes, France",
               "language":"en"
            },
            "fr":{
               "language":"fr",
               "value":"place de Rennes, France"
            },
            "de":{
               "value":"Platz in Frankreich",
               "language":"de"
            }
         },
         "modified":"2022-11-20T21:09:07Z",
         "type":"item",
         "labels":{
            "nl":{
               "value":"Place du Parlement-de-Bretagne",
               "language":"nl"
            },
            "en":{
               "value":"place du Parlement-de-Bretagne",
               "language":"en"
            },
            "fr":{
               "value":"place du Parlement-de-Bretagne",
               "language":"fr"
            },
            "br":{
               "language":"br",
               "value":"plasenn Breujoù Breizh"
            },
            "zh":{
               "value":"布列塔尼议会广场",
               "language":"zh"
            }
         }
      }
   }
}
