#!/bin/bash
# SPDX-FileCopyrightText: 2025 artlog@l0g.eu
# SPDX-License-Identifier: AGPL-3.0-or-later
# header generated by ./metascript.sh header
# metascript_version=v1.1.0

# special case where this tool is not called from this directory
# but derived ...
if [[ "$0" =~ ^(.*)/create_script.sh$ ]]
then
    prefix=${BASH_REMATCH[1]}
else
    prefix=.
    if [[ ! -f metascript.sh ]]
    then
	echo "[FATAL] Can't find metascript.sh, this script should be in same directory"  >&2
	exit 1
    fi
fi
toolsdir=$prefix
pushd $toolsdir >/dev/null
toolsdir=$(pwd)
source metascript.sh
popd >/dev/null

metarun=metarun
# change default to sudo if needed
# metasudo=sudo

while [[ $# > 0 ]]
do
    case "$1" in
	*.sh)
	    script_to_build=$1
	    ;;
	script_to_build=*)
	    script_to_build=${1/script_to_build=}
	    ;;
        *)
           parsemetaarg "$1"
        ;;
    esac
    shift
done

enforce var script_to_build
enforce file $script_to_build does_not_exist

if [[ -z $defer ]]
then
    build_header "$prefix" "$script_to_build" >$script_to_build
else
    build_header "$prefix" "$script_to_build"
fi
$metarun chmod +x $script_to_build

script_usage=${script_to_build}_README.md
cat >$script_usage <<EOF
usage of $script_to_build

./$script_to_build dryrun

remove dryrun to actualy do the action
EOF


