#!/bin/bash
# SPDX-FileCopyrightText: 2026 artlog@l0g.eu
# SPDX-License-Identifier: AGPL-3.0-or-later
# header generated by ../../lib/create_script.sh ../../lib
# metascript_version=v1.2.1

toolsdir=../../lib
pushd $toolsdir >/dev/null
toolsdir=$(pwd)
source metascript.sh
source testlib.sh
popd >/dev/null

encode_decode_test()
{
    reftest=$1
    srcext=$2
    dstext=$3
    if [[ $srcext == "json" ]]
    then
	inform="inform=$srcext"
    else
	inform=
    fi
    if  [[ $dstext == "pp.json" ]]
    then
	indent="indent=spaces"
    else
	indent="indent=spaces:2 space_after"
    fi
    # $json $inform infile=ref/$reftest.$srcext out=${TESTOUT}/$reftest.$dstext 2>${TESTOUT}/$reftest.$dstext.stderr
    echo $json $inform $indent -- ref/$reftest.$srcext ">${TESTOUT}/$reftest.$dstext" "2>${TESTOUT}/$reftest.$dstext.stderr"
    $json $inform $indent -- ref/$reftest.$srcext >${TESTOUT}/$reftest.$dstext 2>${TESTOUT}/$reftest.$dstext.stderr
    check_diff $reftest.$dstext
    # $json $inform infile=ref/$reftest.$srcext out=${TESTOUT}/$reftest.2.$dstext 2>${TESTOUT}/$reftest.2.$dstext.stderr
    echo $json $inform $indent -- ref/$reftest.$srcext ">${TESTOUT}/$reftest.2.$dstext" "2>${TESTOUT}/$reftest.2.$dstext.stderr"
    $json $inform $indent -- ref/$reftest.$srcext >${TESTOUT}/$reftest.2.$dstext 2>${TESTOUT}/$reftest.2.$dstext.stderr

    if true
    then
	# difference can be seen due to out of bound views might not be relevant
	check_diff_files ${TESTOUT}/$reftest.$dstext.stderr ${TESTOUT}/$reftest.2.$dstext.stderr
    fi

    # $json infile=${TESTOUT}/$reftest.$dstext out=${TESTOUT}/$reftest.$srcext 2>${TESTOUT}/$reftest.$srcext.stderr
    echo $json indent=flat -- ${TESTOUT}/$reftest.$dstext ">${TESTOUT}/$reftest.$srcext" "2>${TESTOUT}/$reftest.$srcext.stderr"
    $json indent=flat -- ${TESTOUT}/$reftest.$dstext >${TESTOUT}/$reftest.$srcext 2>${TESTOUT}/$reftest.$srcext.stderr
    check_diff $reftest.$srcext

    log_info "encode decode json $reftest $srcext $dstext '$errors'"
}

runit()
{
    echo "$@"
    $@
}

full_test()
{

    clean_test

    if [[ ! -x $json ]]
    then
	log_error "'$json' is not executable'"
	exit $EXITERROR
    fi

    check_executable "$json"

    mkdir ${TESTOUT}

    $json >${TESTOUT}/usage.txt 2>${TESTOUT}/usage.txt.stderr 

    check_diff usage.txt
    check_diff usage.txt.stderr

    # don't even try to run executable if usage differs.
    check_errors

    $json indent=spaces -- ref/Q3390720.json.pp >${TESTOUT}/Q3390720.json.pp

    check_diff Q3390720.json.pp 


    # fully recursive
    runit $json maxdepth=50 -- ref/syntax_error_101.json

    # fully non recursive
    runit $json maxdepth=20000 -- ref/syntax_error_101.json

    # this shows that mix recursive & non_recursive has hacks
    # $json -d -- ref/syntax_error_101.json

    # mix recursive and non recursive
    runit $json -- ref/syntax_error_101.json

    encode_decode_test backslash json pp.json

    encode_decode_test appendix_a json pp2.json

    # expected fail on flat, done to keep track of improvable behavior
    encode_decode_test missing_coma json pp.json
    
}

json_path() {
    template_dir=../../template/
    # seems to do ntoinh with
    runit $json 'json_path=menu' "arg=[${template_dir}parse1.json]"
    echo
    runit $json 'json_path=menu.value' "arg=[${template_dir}parse1.json]"
    echo
    # expect {"value":"Open","onclick":"OpenDoc()"}
    runit $json 'json_path=menu.popup.menuitem[1]' "arg=[${template_dir}parse1.json]"
    echo
    runit $json 'json_path=menu.popup.menuitem[]' -- "${template_dir}parse1.json"
    echo
    #  https://www.baeldung.com/guide-to-jayway-jsonpath
    runit $json 'json_path=$.tool.jsonpath.creator.location[2]'  -- "${template_dir}baeldung_sample_1.json"
    echo
    runit $json 'json_path=.tool.jsonpath.creator.location[2]'  -- "${template_dir}baeldung_sample_1.json"
    echo
    runit $json 'json_path=tool.jsonpath.creator.location[2]'  -- "${template_dir}baeldung_sample_1.json"
    echo
    runit $json 'json_path=$['"'"'book'"'"'][?]'  -- "${template_dir}baeldung_sample_2.json"
    echo
    runit $json 'json_path=['"'"'book'"'"'][?]'  -- "${template_dir}baeldung_sample_2.json"
    echo
    # bunch of unsupported things.
    runit $json "json_path=\$['book'][?(@['price'] > \$['price range']['medium'])]" -- "${template_dir}baeldung_sample_2.json"
    echo
    runit $json "json_path=['book'][?(@['price'] > ['price range']['medium'])]" -- "${template_dir}baeldung_sample_2.json"
    echo
}


BUILD=../../build
EXITERROR=1

#automeld=meld
automeld=

#base64=$BUILD/base64
#base64=$BUILD/base64_dbg

for fragrance in json
do    
    echo -e "\n\n******** TESTING $fragrance **********\n\n"
    TESTOUT=tmp.$fragrance
    json=$BUILD/$fragrance
    full_test
    json_path
done

check_errors
