LINE = "k2a" SPACE COMPKEYCODE SPACE CHARACTER LF

COMPKEYCODE = KEYCODE / SHIFTCODE

SHIFTCODE = "shift_" KEYCODE

CHARACTER = CHAR

KEYCODE = 1*3(DIGIT)

SPACE = %x20

DIGIT = %x30-39

CHAR = %x1-7f

LF             =  %x0A

