#!/bin/bash

usage()
{
    echo "Will give wordpress directory access in sftp through app/wordpress link in its home directory"
    echo "user=<user>"
}

# copied from https://yunohost.org/fr/sftp_on_apps
# need a THE_USER parameter
create_wordpress_link()
{
    if [[ -z $THE_USER ]]
    then
	echo "[FATAL] expected one parameter THE_USER , please check bash script" >&2
    fi
    mkdir -p /home/$THE_USER/apps/wordpress
    touch /home/$THE_USER/.nobackup
    mount --bind /var/www/wordpress /home/$THE_USER/apps/wordpress
    # add an initial \n if ever /etc/fstab was not terminated by one \n
    echo -e "\n# generated by $0 \n/var/www/wordpress /home/$THE_USER/apps/wordpress none defaults,bind 0 0" >> /etc/fstab
    find /var/www/wordpress -type d -exec chmod g+s {} \;

    setfacl -R -m u:wordpress:rwX /var/www/wordpress
    setfacl -R -d -m u:wordpress:rwX /var/www/wordpress
    setfacl -m u:wordpress:r-- /var/www/wordpress/wp-config.php

    setfacl -R -m u:$THE_USER:rwX /var/www/wordpress
    setfacl -R -d -m u:$THE_USER:rwX /var/www/wordpress
}

while [[ $# > 0 ]]
do
    case $1 in
	user=*)
	    THE_USER=${1/user=//}	    
	    ;;
	*)
	    echo "[ERROR] unreocgnized argument $1" >&2
	    usage
	    exit 1
    esac
    shift  
done

if [[ -z $THE_USER ]]
then
    echo "[ERROR] expected user= user" >&2
    usage
    exit 1
fi

if [[ ! -d /home/$THE_USER/apps/wordpress ]]
then
    create_wordpress_link
else
    echo "[WARNING] /home/$THE_USER/apps/wordpress already exists, not recreated !" >&2
fi
