#!/bin/bash
#
# Generates to stdout an ant project build.xml content using some parameters from project_params
#
# TODO remove it since ant build.xml will parse project_params itself
# now used only to extract project_name
#
# this is used by 4java.makefile for build.xml target

usage()
{
    head -n 4 $0 
}

PROJECT_PARAMS=./project_params
if [[ -f $PROJECT_PARAMS ]]
then
    # extract only project_name
    source $PROJECT_PARAMS
    project_name=$(grep project_name project_params)
    project_name=${project_name/project_name=/}
    echo "project_name=$project_name" >&2
else
    echo "[ERROR] missing $PROJECT_PARAMS " >&2
    usage
    exit 1
fi

# TODO reuse internal tsamp ${DSTAMP} ( after review i do't recall what is wanted to do here )

# don't set basedir as absolute but as '.' relative to git project.

cat <<EOF
<!-- for document on apache ant see https://ant.apache.org/manual-1.9.x/index.html -->
<project name="$project_name" default="$project_default" basedir=".">
    <description>
        $project_name build
        autogenerated build file by $0 script 
    </description>
  <!-- set global properties for this build -->
  <property name="src" location="java"/>
  <property name="build" location="build"/>
  <property name="dist"  location="dist"/>
  <!-- Fill me please / todo since HARDCODED
  <property name="artgraphicslib" value="artgaphics-0.1.0"/>
  -->
  <target name="gather_project_params">
    <!-- original source parameter is in project_params project_version -->
    <loadfile property="distversion" srcfile="\${basedir}/project_params">
      <filterchain>
        <tokenfilter>
          <containsregex
              pattern="project_version=([0-9.]+)$"
              replace="\1" />
            </tokenfilter>
      </filterchain>
    </loadfile>
    <echo message="distversion : \${distversion}" />
  </target>

  <target name="init">
    <!-- Create the time stamp -->
    <tstamp/>
    <!-- Create the build directory structure used by compile -->
    <mkdir dir="\${build}"/>
  </target>

  <target name="compile" depends="init"
        description="compile the source " >
    <!-- Compile the java code from \${src} into \${build} -->
EOF

if [[ -z $java_target ]]
then
    echo '   <javac srcdir="${src}" destdir="${build}" includeantruntime="false">'
else
    echo "   <javac target=\"$java_target\" source=\"$java_target\" srcdir=\"\${src}\" destdir=\"\${build}\" includeantruntime=\"false\"><compilerarg value=\"-Xlint:-options\">"
fi
echo "<!-- suggestion "
excludes="org/artisanlogiciel/games/javafx/*"
for exclude in "$excludes"
do
    echo "      <exclude name=\"$exclude\"/>"
done
echo "-->"
echo "     <compilerarg value=\"-Xlint:deprecation,unchecked\" />"
echo "   </javac>"

cat <<EOF
  </target>

  <target name="dist" depends="gather_project_params,compile"
        description="generate the distribution" >
    <!-- Create the distribution directory -->
    <mkdir dir="\${dist}/lib"/>

    <!-- Put everything in \${build} into the ${project_name}-\${distversion}.jar file  ( \${DSTAMP} not used yet )-->
    <jar jarfile="\${dist}/lib/${project_name}-\${distversion}.jar" basedir="\${build}">
            <manifest>
                <attribute name="Main-Class" value="$project_mainclass"/>
    <!-- suggestion
		<attribute name="Class-Path" value="libs/\${artgraphicslib}.jar"/>
    -->
            </manifest>
	    <fileset dir="lang" includes="**" />
     </jar>
  </target>

  <target name="clean"
        description="clean up" >
    <!-- Delete the \${build} and \${dist} directory trees -->
    <delete dir="\${build}"/>
    <delete dir="\${dist}"/>
  </target>
</project>
EOF
